# Question 7

In [1]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to /home/corentin/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/corentin/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/corentin/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/corentin/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [1]:
import pandas as pd

emotag_df = pd.read_csv("EmoTag1200-scores.csv")

# Normalization of the 'name' column
emotag_df["normalized_name"] = emotag_df["name"].str.lower().str.replace(" ", "_")

print(emotag_df.shape)
display(emotag_df.head())

(150, 12)

,unicode,emoji,name,anger,anticipation,disgust,fear,joy,sadness,surprise,trust,normalized_name
0,1F308,🌈,rainbow,0.00,0.28,0.00,0.00,0.69,0.06,0.22,0.33,rainbow
1,1F319,🌙,crescent moon,0.00,0.31,0.00,0.00,0.25,0.00,0.06,0.25,crescent_moon
2,1F31A,🌚,new moon face,0.06,0.08,0.17,0.06,0.42,0.19,0.06,0.11,new_moon_face
3,1F31E,🌞,sun with face,0.00,0.22,0.00,0.00,0.78,0.00,0.11,0.22,sun_with_face
4,1F31F,🌟,glowing star,0.00,0.28,0.00,0.00,0.53,0.00,0.25,0.31,glowing_star

In [2]:
import os
from tqdm import tqdm
tweet_dir = "tweets"
df_tweets_dict = {}

for file in tqdm(os.listdir(tweet_dir)):
    if not file.endswith(".csv"):
        continue
    # Example : backhand_index_pointing_right.csv -> backhand_index_pointing_right
    emoji_name = file[:-4]
    path = os.path.join(tweet_dir, file)
    print(f"Loading {path}...")
    df = pd.read_csv(
        path,
        encoding='utf-8',
        engine='python',
        on_bad_lines='skip'
    )
    
    # Cleaning : drop rows with NaN in 'Text' column
    if "Text" not in df.columns:
        print(f"colomn 'Text' absent in {file}")
        continue
    df = df.dropna(subset=["Text"])
    
    df_tweets_dict[emoji_name] = df["Text"]

print(f"{len(df_tweets_dict)} emojis loaded.")
for k, v in list(df_tweets_dict.items())[:3]:
    print(f"{k}: {len(v)} tweets")

  0%|          | 0/43 [00:00<?, ?it/s]

  2%|▏         | 1/43 [00:00<00:04,  8.94it/s]

Loading tweets/face_holding_back_tears.csv...
Loading tweets/face_savoring_food.csv...

  9%|▉         | 4/43 [00:00<00:03, 10.21it/s]

Loading tweets/thumbs_up.csv...
Loading tweets/melting_face.csv...
Loading tweets/check_mark_button.csv...

 14%|█▍        | 6/43 [00:00<00:03,  9.77it/s]

Loading tweets/winking_face.csv...
Loading tweets/backhand_index_pointing_right.csv...

 21%|██        | 9/43 [00:00<00:03,  9.68it/s]

Loading tweets/rolling_on_the_floor_laughing.csv...
Loading tweets/thinking_face.csv...
Loading tweets/folded_hands.csv...

 26%|██▌       | 11/43 [00:01<00:03,  9.83it/s]

Loading tweets/red_heart.csv...
Loading tweets/sparkles.csv...
Loading tweets/skull.csv...

 35%|███▍      | 15/43 [00:01<00:02, 10.92it/s]

Loading tweets/enraged_face.csv...
Loading tweets/smiling_face_with_sunglasses.csv...
Loading tweets/pile_of_poo.csv...

 40%|███▉      | 17/43 [00:01<00:02, 10.45it/s]

Loading tweets/rabbit_face.csv...
Loading tweets/eyes.csv...
Loading tweets/face_with_tears_of_joy.csv...

 44%|████▍     | 19/43 [00:01<00:02, 11.33it/s]

Loading tweets/ghost.csv...
Loading tweets/white_heart.csv...

 53%|█████▎    | 23/43 [00:02<00:01, 10.91it/s]

Loading tweets/cooking.csv...
Loading tweets/hot_face.csv...
Loading tweets/check_mark.csv...

 58%|█████▊    | 25/43 [00:02<00:01, 10.92it/s]

Loading tweets/grinning_face_with_sweat.csv...
Loading tweets/smiling_face_with_hearts.csv...
Loading tweets/fearful_face.csv...

 67%|██████▋   | 29/43 [00:02<00:01, 11.27it/s]

Loading tweets/clown_face.csv...
Loading tweets/hatching_chick.csv...
Loading tweets/partying_face.csv...

 72%|███████▏  | 31/43 [00:02<00:01, 10.81it/s]

Loading tweets/loudly_crying_face.csv...
Loading tweets/smiling_face_with_tear.csv...
Loading tweets/smiling_face_with_heart-eyes.csv...

 77%|███████▋  | 33/43 [00:03<00:00, 11.57it/s]

Loading tweets/party_popper.csv...
Loading tweets/smiling_face_with_halo.csv...

 86%|████████▌ | 37/43 [00:03<00:00, 11.05it/s]

Loading tweets/egg.csv...
Loading tweets/smiling_face.csv...
Loading tweets/middle_finger.csv...

 91%|█████████ | 39/43 [00:03<00:00, 11.27it/s]

Loading tweets/sun.csv...
Loading tweets/saluting_face.csv...

 95%|█████████▌| 41/43 [00:03<00:00, 10.31it/s]

Loading tweets/fire.csv...
Loading tweets/rabbit.csv...
Loading tweets/face_with_steam_from_nose.csv...

100%|██████████| 43/43 [00:04<00:00, 10.55it/s]

43 emojis loaded.
face_holding_back_tears: 20000 tweets
face_savoring_food: 20000 tweets
thumbs_up: 20000 tweets

In [11]:
import gensim.downloader as api

wv = api.load("glove-wiki-gigaword-100")  # word vectors

print("Size of vocabulary :", len(wv))
print("similarity example:", wv.similarity("happy", "joy"))

Size of vocabulary : 400000
similarity example: 0.5188851

In [ ]:
import pandas as pd, numpy as np
from gensim import corpora
from gensim.models import LdaModel, KeyedVectors
from gensim.utils import simple_preprocess
from nltk.corpus import stopwords
from sklearn.metrics.pairwise import cosine_similarity
from scipy.stats import pearsonr
from tqdm import tqdm
import re

stop = set(stopwords.words('english'))

def preprocess(text):
    if not isinstance(text, str):
        return []
    # delete URLs, mentions, hashtags, numbers, punctuation, HTML entities
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#\w+", "", text)
    text = re.sub(r"&amp;", " ", text)     # HTML entity
    text = re.sub(r"[^A-Za-z\s]", " ", text)  # only letters / spaces
    toks = simple_preprocess(text, deacc=True)
    toks = [t for t in toks if t not in stop and len(t) > 2]
    return toks

def lda_one_topic_topk_for_emoji(df_texts, wv, num_words=8):
    # preprocess texts
    texts = [preprocess(t) for t in df_texts if isinstance(t, str)]
    dictionary = corpora.Dictionary(texts)
    dictionary.filter_extremes(no_below=5, no_above=0.5)
    
    if len(dictionary) == 0:
        return []

    corpus = [dictionary.doc2bow(t) for t in texts if len(t) > 0]

    if not corpus or all(len(doc) == 0 for doc in corpus):
        return []

    # LDA
    lda = LdaModel(
        corpus=corpus,
        id2word=dictionary,
        num_topics=1,
        random_state=42,
        iterations=100,
        passes=5,
        minimum_probability=0.0
    )

    topic = lda.show_topic(0, topn=num_words)  # [('word', weight), ...]
    return topic

emotion_names = ['anger','anticipation','disgust','fear','joy','sadness','surprise','trust']

def keywords_to_emotion_scores(topic_words, wv):
    # topic_words : list of (word, weight)
    # wv : keyedvectors supporting similarity; fallback: cosine on embeddings if using transformer
    # Return vector of length 8
    scores = np.zeros(len(emotion_names))
    for word, w in topic_words:
        # compute similarity of word to each emotion name
        s_list = []
        for i, emo in enumerate(emotion_names):
            try:
                sim = wv.similarity(word, emo)
            except Exception:
                # if OOV, try lowercased/emotion synonyms or set sim=0
                sim = 0.0
            scores[i] += sim * w
    # normalize
    if scores.sum() != 0:
        scores = scores / (np.abs(scores).sum())
    return scores

results = []
for emoji_name, texts in tqdm(df_tweets_dict.items()):
    topic = lda_one_topic_topk_for_emoji(texts, wv, num_words=8)
    pred_vec = keywords_to_emotion_scores(topic, wv)  # predicted emotion vector
    # get ground truth vector from emotag_df (match on name or normalized)
    row = emotag_df[emotag_df['normalized_name']==emoji_name]
    if row.empty:
        gt = np.zeros(len(emotion_names))
    else:
        gt = row[emotion_names].values.flatten()
        if gt.sum() != 0:
            gt = gt / gt.sum()
    # similarity / correlation
    cos = cosine_similarity(pred_vec.reshape(1,-1), gt.reshape(1,-1))[0,0]
    try:
        pearson = pearsonr(pred_vec, gt)[0]
    except Exception:
        pearson = np.nan
    results.append({'emoji':emoji_name, 'lda_keywords':[w for w,_ in topic],
                    'pred_vec':pred_vec, 'gt_vec':gt, 'cosine':cos, 'pearson':pearson})
res_df = pd.DataFrame(results)

  0%|          | 0/43 [00:00<?, ?it/s]/tmp/ipykernel_105680/1548987933.py:109: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearson = pearsonr(pred_vec, gt)[0]
  7%|▋         | 3/43 [00:20<04:31,  6.79s/it]/tmp/ipykernel_105680/1548987933.py:109: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearson = pearsonr(pred_vec, gt)[0]
 16%|█▋        | 7/43 [00:53<04:48,  8.02s/it]/tmp/ipykernel_105680/1548987933.py:109: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearson = pearsonr(pred_vec, gt)[0]
 19%|█▊        | 8/43 [01:00<04:30,  7.74s/it]/tmp/ipykernel_105680/1548987933.py:109: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearson = pearsonr(pred_vec, gt)[0]
 30%|███       | 13/43 [01:36<03:30,  7.01s/it]/tmp/ipykernel_105680/1548987933.py:109: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearson = pearsonr(pred_vec, gt)[0]
 37%|███▋      | 16/43 [02:01<03:37,  8.07s/it]/tmp/ipykernel_105680/1548987933.py:109: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearson = pearsonr(pred_vec, gt)[0]
 47%|████▋     | 20/43 [02:30<02:47,  7.27s/it]/tmp/ipykernel_105680/1548987933.py:109: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearson = pearsonr(pred_vec, gt)[0]
 49%|████▉     | 21/43 [02:37<02:42,  7.40s/it]/tmp/ipykernel_105680/1548987933.py:109: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearson = pearsonr(pred_vec, gt)[0]
 51%|█████     | 22/43 [02:45<02:39,  7.59s/it]/tmp/ipykernel_105680/1548987933.py:109: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearson = pearsonr(pred_vec, gt)[0]
 58%|█████▊    | 25/43 [03:07<02:11,  7.28s/it]/tmp/ipykernel_105680/1548987933.py:109: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearson = pearsonr(pred_vec, gt)[0]
 63%|██████▎   | 27/43 [03:20<01:48,  6.79s/it]/tmp/ipykernel_105680/1548987933.py:109: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearson = pearsonr(pred_vec, gt)[0]
 65%|██████▌   | 28/43 [03:27<01:42,  6.82s/it]/tmp/ipykernel_105680/1548987933.py:109: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearson = pearsonr(pred_vec, gt)[0]
 67%|██████▋   | 29/43 [03:33<01:35,  6.80s/it]/tmp/ipykernel_105680/1548987933.py:109: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearson = pearsonr(pred_vec, gt)[0]
 72%|███████▏  | 31/43 [03:47<01:20,  6.70s/it]/tmp/ipykernel_105680/1548987933.py:109: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearson = pearsonr(pred_vec, gt)[0]
 81%|████████▏ | 35/43 [04:13<00:52,  6.53s/it]/tmp/ipykernel_105680/1548987933.py:109: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearson = pearsonr(pred_vec, gt)[0]
 86%|████████▌ | 37/43 [04:26<00:40,  6.69s/it]/tmp/ipykernel_105680/1548987933.py:109: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearson = pearsonr(pred_vec, gt)[0]
 91%|█████████ | 39/43 [04:40<00:27,  6.78s/it]/tmp/ipykernel_105680/1548987933.py:109: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearson = pearsonr(pred_vec, gt)[0]
 95%|█████████▌| 41/43 [04:54<00:13,  6.81s/it]/tmp/ipykernel_105680/1548987933.py:109: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  pearson = pearsonr(pred_vec, gt)[0]
100%|██████████| 43/43 [05:08<00:00,  7.18s/it]

In [16]:
display(res_df.sort_values(by='cosine', ascending=False))

,emoji,lda_keywords,pred_vec,gt_vec,cosine,pearson
40,fire,"[one, like, love, get, easter, time, see, happy]","[0.11867254972939123, 0.11580920822936336, 0.0...","[0.24867724867724864, 0.1164021164021164, 0.07...",0.902134,0.370875
24,grinning_face_with_sweat,"[like, one, get, know, time, think, people, even]","[0.12632175125689526, 0.10864706296727107, 0.0...","[0.0427807486631016, 0.23529411764705882, 0.03...",0.870220,0.425845
26,fearful_face,"[like, one, people, get, know, see, would, time]","[0.1264226761274811, 0.11094121465343132, 0.06...","[0.0576271186440678, 0.13220338983050847, 0.11...",0.829056,0.383439
2,thumbs_up,"[good, great, like, well, one, get, see, thanks]","[0.11908193824270268, 0.117297152197907, 0.058...","[0.06470588235294117, 0.22941176470588234, 0.0...",0.803988,0.238561
11,sparkles,"[happy, easter, love, like, one, thank, day, t...","[0.1128653643901034, 0.11995206989602063, 0.06...","[0.0, 0.21176470588235294, 0.0, 0.035294117647...",0.801965,0.619130
12,skull,"[like, one, even, bro, get, people, know, got]","[0.12587934535471654, 0.1032665661222621, 0.07...","[0.11176470588235295, 0.0823529411764706, 0.14...",0.791212,0.272769
17,eyes,"[see, like, one, get, know, new, time, look]","[0.12059625133421575, 0.11827945656014571, 0.0...","[0.058091286307053944, 0.3360995850622407, 0.0...",0.785651,0.390222
9,folded_hands,"[easter, thank, happy, please, god, day, love,...","[0.1071078008759467, 0.11519083941044461, 0.06...","[0.034883720930232565, 0.25581395348837216, 0....",0.772345,0.251638
19,ghost,"[like, one, love, good, ghost, get, day, time]","[0.1202190582305102, 0.1095104946068943, 0.062...","[0.07534246575342465, 0.05479452054794521, 0.0...",0.764643,0.639362
33,party_popper,"[happy, birthday, congratulations, day, easter...","[0.10494551891147846, 0.12925224356085033, 0.0...","[0.0, 0.15865384615384615, 0.0, 0.0, 0.4423076...",0.760313,0.722009
32,smiling_face_with_heart-eyes,"[love, beautiful, easter, happy, like, one, lo...","[0.11117284264877013, 0.11106869190843156, 0.0...","[0.0, 0.14485981308411214, 0.0, 0.0, 0.3878504...",0.751059,0.560964
5,winking_face,"[like, good, one, know, get, easter, happy, see]","[0.11513512500076387, 0.11678017068646859, 0.0...","[0.0, 0.2485207100591716, 0.0, 0.0, 0.26035502...",0.745976,0.254135
36,smiling_face,"[thank, good, day, like, love, happy, much, one]","[0.11418615826159374, 0.11250620898893472, 0.0...","[0.0, 0.1818181818181818, 0.0, 0.0, 0.43290043...",0.711624,0.457332
34,smiling_face_with_halo,"[love, good, like, thank, one, god, day, get]","[0.11849351004632395, 0.10217305834207409, 0.0...","[0.0, 0.18235294117647058, 0.0, 0.0, 0.4235294...",0.683252,0.363358
10,red_heart,"[happy, easter, love, thank, day, good, much, ...","[0.10943421533607987, 0.12246978232254425, 0.0...","[0.0, 0.1935483870967742, 0.0, 0.0, 0.37096774...",0.674257,0.313293
6,backhand_index_pointing_right,"[check, live, get, new, free, shop, time, prod...","[0.12091047396295235, 0.1377726438111834, 0.04...","[0.11764705882352941, 0.49019607843137253, 0.0...",0.635785,0.314888
38,sun,"[good, day, morning, great, tuesday, happy, to...","[0.11327733126784216, 0.1366530148103678, 0.05...","[0.0, 0.2558139534883721, 0.0, 0.0, 0.51162790...",0.629831,0.281647
18,face_with_tears_of_joy,"[like, one, liverpool, get, know, even, see, e...","[0.12184123751321371, 0.11621561072179097, 0.0...","[0.0, 0.0955056179775281, 0.033707865168539325...",0.616758,0.163383
1,face_savoring_food,"[like, good, love, delicious, one, get, time, ...","[0.1166448794820063, 0.11256128433072156, 0.06...","[0.0, 0.3032258064516129, 0.0, 0.0, 0.50322580...",0.607519,0.202341
23,check_mark,"[done, day, winner, get, prize, like, check, c...","[0.11747217028445261, 0.11528801444258253, 0.0...","[0.0, 0.3333333333333333, 0.0, 0.0, 0.18666666...",0.590487,0.174258
14,smiling_face_with_sunglasses,"[easter, like, happy, one, good, day, get, time]","[0.11395935454555028, 0.129990356565867, 0.051...","[0.0, 0.16176470588235292, 0.0, 0.0, 0.5514705...",0.583495,0.179079
4,check_mark_button,"[usdt, like, follow, denet, giveaway, done, ar...","[0.12592300779849122, 0.1305372144681999, 0.06...","[0.0, 0.37349397590361444, 0.0, 0.0, 0.2289156...",0.573799,0.024268
30,loudly_crying_face,"[like, one, get, love, even, know, got, really]","[0.124508985216759, 0.1050519830257537, 0.0713...","[0.10232558139534884, 0.037209302325581395, 0....",0.556991,-0.413831
15,pile_of_poo,"[like, people, get, one, know, bull, piece, full]","[0.12550230543412771, 0.10869699348118006, 0.0...","[0.09722222222222222, 0.05555555555555555, 0.4...",0.543465,-0.545521
42,face_with_steam_from_nose,"[like, get, one, time, back, know, need, see]","[0.12442769863562911, 0.11589780058344061, 0.0...","[0.39062499999999994, 0.057291666666666664, 0....",0.513378,-0.488755
35,egg,"[happy, egg, eggs, weekend, day, good, everyon...","[0.11313977392018439, 0.12721252514139875, 0.0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,NaN
37,middle_finger,"[like, people, one, get, fuck, know, never, good]","[0.12612833667017637, 0.09930569880392633, 0.0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,NaN
39,saluting_face,"[one, good, get, like, thank, see, time, day]","[0.1168869711772784, 0.11890403471758441, 0.06...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,NaN
41,rabbit,"[day, everyone, good, hope, love, bunny, thank...","[0.11802425959801627, 0.11510299253479184, 0.0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,NaN
31,smiling_face_with_tear,"[like, one, get, time, see, really, want, love]","[0.12352543197181289, 0.10963804463330097, 0.0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,NaN
0,face_holding_back_tears,"[love, thank, like, much, one, see, happy, rea...","[0.11912233410733344, 0.10412245142744055, 0.0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,NaN
29,partying_face,"[happy, birthday, day, easter, hope, like, tod...","[0.10681464195493844, 0.1323990148821866, 0.05...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,NaN
28,hatching_chick,"[day, hope, everyone, family, love, sunday, go...","[0.12243063597197062, 0.11675246619734699, 0.0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,NaN
27,clown_face,"[like, people, one, clown, know, get, even, ri...","[0.13096685744010822, 0.09800851409349154, 0.0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,NaN
25,smiling_face_with_hearts,"[easter, happy, love, thank, day, good, much, ...","[0.10939262035688692, 0.12259727956360561, 0.0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,NaN
22,hot_face,"[hot, like, one, love, get, good, know, look]","[0.12542926780263106, 0.11247292387081263, 0.0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,NaN
20,white_heart,"[love, thank, good, day, happy, like, much, one]","[0.11656912668091655, 0.10884365824781046, 0.0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,NaN
16,rabbit_face,"[day, bunny, hope, everyone, love, family, tha...","[0.11990549705563866, 0.11081750738137253, 0.0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,NaN
13,enraged_face,"[like, people, get, one, would, know, time, even]","[0.1294227045745628, 0.11060935871036302, 0.06...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,NaN
8,thinking_face,"[like, think, one, would, get, people, know, m...","[0.12612523790089203, 0.1071620690032987, 0.06...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,NaN
7,rolling_on_the_floor_laughing,"[like, one, know, get, would, people, got, even]","[0.1272854663906146, 0.10883056409272425, 0.06...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,NaN
3,melting_face,"[like, one, get, time, know, even, love, really]","[0.1246888335158429, 0.10826192203898158, 0.06...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,NaN
21,cooking,"[hour, golden, streaming, mark, happy, chain, ...","[0.1137502181781529, 0.13606626300431007, 0.04...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",0.000000,NaN

# Question 8

In [12]:
import pandas as pd
import numpy as np
from tqdm import tqdm
import sys
sys.modules["torchvision"] = None  # workaround for import error
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import re
from gensim.utils import simple_preprocess
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer




# Keep only those emojis
common_emojis = set(df_tweets_dict.keys()) & set(emotag_df["normalized_name"])
df_tweets_dict = {k: v for k, v in df_tweets_dict.items() if k in common_emojis}
emotag_df = emotag_df[emotag_df["normalized_name"].isin(common_emojis)].reset_index(drop=True)

print(f"{len(common_emojis)} emojis kept (present in EmoTag).")

stop = set(stopwords.words("english"))
extra_stop = {"amp", "rt", "im", "u", "ur", "dont", "cant", "youre", "ive", "lol", "omg"}
stop |= extra_stop

def preprocess(text):
    if not isinstance(text, str):
        return []
    # delete URLs, mentions, hashtags, numbers, punctuation, HTML entities
    text = re.sub(r"http\S+|www\S+|https\S+", "", text)
    text = re.sub(r"@\w+|#\w+", "", text)
    text = re.sub(r"&amp;", " ", text)     # HTML entité
    text = re.sub(r"[^A-Za-z\s]", " ", text)  # garde que lettres / espaces
    toks = simple_preprocess(text, deacc=True)
    toks = [t for t in toks if t not in stop and len(t) > 2]
    return toks

# Load sentence-transformer model
embedder = SentenceTransformer("all-MiniLM-L6-v2")

def bertopic_for_emoji(texts, nr_topics="auto", top_n_words=8, sample_size=3000):
    """Compute BERTopic on tweets of one emoji (downsampled)."""
    # Downsample to speed up (3k tweets max)
    if len(texts) > sample_size:
        texts = texts.sample(sample_size, random_state=42)
    else:
        texts = texts.dropna()

    texts = [" ".join(preprocess(t)) for t in texts if isinstance(t, str) and len(t) > 0]
    texts = [t for t in texts if len(t.split()) > 2]  # we ignore too-short tweets

    if len(texts) < 20:
        return None, None, None, None, None

    embeddings = embedder.encode(texts, show_progress_bar=False, batch_size=64)
    vectorizer_model = CountVectorizer(stop_words="english")

    topic_model = BERTopic(
        nr_topics=nr_topics,
        min_topic_size=50,
        verbose=False,
        calculate_probabilities=True,
        vectorizer_model=vectorizer_model,
    )

    topics, probs = topic_model.fit_transform(texts, embeddings)
    freq = pd.Series(topics).value_counts()
    top_topic = int(freq.index[0])
    words = topic_model.get_topic(top_topic)[:top_n_words] if topic_model.get_topic(top_topic) else []
    return topic_model, top_topic, words, topics, probs

emotion_names = ['anger','anticipation','disgust','fear','joy','sadness','surprise','trust']

def keywords_to_emotion_scores(topic_words, wv):
    scores = np.zeros(len(emotion_names))
    for word, w in topic_words:
        for i, emo in enumerate(emotion_names):
            try:
                sim = wv.similarity(word, emo)
            except Exception:
                sim = 0.0
            scores[i] += sim * w
    if scores.sum() != 0:
        scores = scores / np.abs(scores).sum()
    return scores

bert_results = []

for emoji_name, texts in tqdm(df_tweets_dict.items()):
    tm, top_topic, words, topics, probs = bertopic_for_emoji(texts)
    if not words:
        continue

    topic_words = [(w, score) for w, score in words]
    pred_vec = keywords_to_emotion_scores(topic_words, wv)

    row = emotag_df[emotag_df["normalized_name"] == emoji_name]
    gt = row[emotion_names].values.flatten() if not row.empty else np.zeros(len(emotion_names))
    if gt.sum() != 0:
        gt = gt / gt.sum()

    cos = cosine_similarity(pred_vec.reshape(1, -1), gt.reshape(1, -1))[0, 0]
    bert_results.append({
        "emoji": emoji_name,
        "topic_words": [w for w, _ in topic_words],
        "pred_vec": pred_vec,
        "gt_vec": gt,
        "cosine": cos
    })

bert_df = pd.DataFrame(bert_results)
print(f"BERTopic completed for {len(bert_df)} emojis.")

bert_df.to_csv("bertopic_results.csv", index=False)
display(bert_df.sort_values("cosine", ascending=False))

25 emojis kept (present in EmoTag).

100%|██████████| 25/25 [54:43<00:00, 131.32s/it]

BERTopic completed for 25 emojis.

,emoji,topic_words,pred_vec,gt_vec,cosine
23,fire,"[love, like, time, got, good, today, let, new]","[0.1204446843639845, 0.11294473042822008, 0.06...","[0.24867724867724864, 0.1164021164021164, 0.07...",0.900336
15,grinning_face_with_sweat,"[like, time, know, good, people, think, day, r...","[0.12116009865414787, 0.11225450609740371, 0.0...","[0.0427807486631016, 0.23529411764705882, 0.03...",0.882408
16,fearful_face,"[like, know, people, going, day, said, got, god]","[0.12390491064336769, 0.10760047028754087, 0.0...","[0.0576271186440678, 0.13220338983050847, 0.11...",0.822215
1,thumbs_up,"[good, like, great, thank, thanks, know, time,...","[0.11395319870119397, 0.11561549867955563, 0.0...","[0.06470588235294117, 0.22941176470588234, 0.0...",0.806486
8,skull,"[like, know, people, shit, think, got, time, l...","[0.12604867735574934, 0.09963470483763062, 0.0...","[0.11176470588235295, 0.0823529411764706, 0.14...",0.803134
7,sparkles,"[like, day, know, new, good, love, really, let]","[0.12142492485700308, 0.11123086647028846, 0.0...","[0.0, 0.21176470588235294, 0.0, 0.035294117647...",0.770080
5,folded_hands,"[thank, good, god, know, love, day, bless, like]","[0.11281533961979011, 0.09595072361258387, 0.0...","[0.034883720930232565, 0.25581395348837216, 0....",0.769598
11,eyes,"[like, know, got, new, want, look, love, think]","[0.12033303656067318, 0.10678360700092857, 0.0...","[0.058091286307053944, 0.3360995850622407, 0.0...",0.760707
13,ghost,"[like, time, good, love, day, know, got, today]","[0.11722544252345211, 0.11446377382813708, 0.0...","[0.07534246575342465, 0.05479452054794521, 0.0...",0.754700
19,party_popper,"[birthday, happy, congratulations, day, thank,...","[0.10821034196097924, 0.12479761362908527, 0.0...","[0.0, 0.15865384615384615, 0.0, 0.0, 0.4423076...",0.750179
18,smiling_face_with_heart-eyes,"[love, like, good, day, cute, beautiful, look,...","[0.11085279282828388, 0.10793986153741573, 0.0...","[0.0, 0.14485981308411214, 0.0, 0.0, 0.3878504...",0.745898
3,winking_face,"[like, time, know, good, need, love, think, let]","[0.12174782919719514, 0.105958333197179, 0.066...","[0.0, 0.2485207100591716, 0.0, 0.0, 0.26035502...",0.730547
21,smiling_face,"[like, love, happy, time, thank, day, great, g...","[0.1136355636691906, 0.11232957375662517, 0.06...","[0.0, 0.1818181818181818, 0.0, 0.0, 0.43290043...",0.713798
6,red_heart,"[love, day, happy, good, thank, easter, time, ...","[0.1115245487439266, 0.12016505675442357, 0.06...","[0.0, 0.1935483870967742, 0.0, 0.0, 0.37096774...",0.682865
20,smiling_face_with_halo,"[like, love, thank, good, happy, know, time, god]","[0.11415031258527311, 0.10088276583684032, 0.0...","[0.0, 0.18235294117647058, 0.0, 0.0, 0.4235294...",0.681223
4,backhand_index_pointing_right,"[check, shop, new, product, starting, free, ea...","[0.11684874033371866, 0.16170268199441187, 0.0...","[0.11764705882352941, 0.49019607843137253, 0.0...",0.673875
22,sun,"[like, sun, weather, summer, today, love, day,...","[0.11761358807956503, 0.14284960500383387, 0.0...","[0.0, 0.2558139534883721, 0.0, 0.0, 0.51162790...",0.632646
12,face_with_tears_of_joy,"[like, know, time, people, love, got, shit, ri...","[0.12755949735050165, 0.09780942731445708, 0.0...","[0.0, 0.0955056179775281, 0.033707865168539325...",0.627493
0,face_savoring_food,"[love, good, today, like, delicious, day, eat,...","[0.11452823753604818, 0.1175829845789261, 0.06...","[0.0, 0.3032258064516129, 0.0, 0.0, 0.50322580...",0.621684
2,check_mark_button,"[like, follow, day, wts, easter, free, today, ...","[0.11170071018172735, 0.1427573522636772, 0.04...","[0.0, 0.37349397590361444, 0.0, 0.0, 0.2289156...",0.617631
14,check_mark,"[day, winner, today, link, prize, claim, like,...","[0.11753739091626458, 0.11959110625470756, 0.0...","[0.0, 0.3333333333333333, 0.0, 0.0, 0.18666666...",0.604842
9,smiling_face_with_sunglasses,"[like, good, make, know, love, time, day, life]","[0.11904701709964045, 0.11076141384722481, 0.0...","[0.0, 0.16176470588235292, 0.0, 0.0, 0.5514705...",0.582654
17,loudly_crying_face,"[like, know, really, time, good, love, literal...","[0.11960297472830433, 0.10317340723710318, 0.0...","[0.10232558139534884, 0.037209302325581395, 0....",0.566574
10,pile_of_poo,"[like, know, people, bull, piece, good, think,...","[0.12112383862481439, 0.1064927467444592, 0.06...","[0.09722222222222222, 0.05555555555555555, 0.4...",0.546667
24,face_with_steam_from_nose,"[like, time, got, love, better, know, people, ...","[0.12286394553758735, 0.10256954884485206, 0.0...","[0.39062499999999994, 0.057291666666666664, 0....",0.524057

In [13]:
tm.visualize_topics()     
tm.visualize_barchart(top_n_topics=10)
tm.visualize_term_rank()

# Question 9

Python 3.7.12

In [ ]:
import sys
import os
PROJECT_ROOT = "/home/corentin/Documents/Oulu/textMining/project/torchMoji/torchMoji/"
if PROJECT_ROOT not in sys.path:    
    PARENT_DIR = os.path.dirname(PROJECT_ROOT.rstrip(os.path.sep))
    if PARENT_DIR not in sys.path:
        sys.path.append(PARENT_DIR)

In [ ]:
import sys
import os
import torch
import numpy as np
import pandas as pd
from tqdm import tqdm
import json
import emoji as emoji_lib

from torchmoji.sentence_tokenizer import SentenceTokenizer
from torchmoji.model_def import torchmoji_emojis
from torchmoji.global_variables import PRETRAINED_PATH, VOCAB_PATH

print("Loading TorchMoji model and vocabulary...")
with open(VOCAB_PATH, 'r') as f:
    vocabulary = json.load(f)

maxlen = 30
st = SentenceTokenizer(vocabulary, maxlen)
model = torchmoji_emojis(PRETRAINED_PATH)
model.eval()
print("Model loaded.")

EMOJIS = ":joy: :unamused: :weary: :sob: :heart_eyes: \
:pensive: :ok_hand: :blush: :heart: :smirk: \
:grin: :notes: :flushed: :100: :sleeping: \
:relieved: :relaxed: :raised_hands: :two_hearts: :expressionless: \
:sweat_smile: :pray: :confused: :kissing_heart: :heartbeat: \
:neutral_face: :information_desk_person: :disappointed: :see_no_evil: :tired_face: \
:v: :sunglasses: :rage: :thumbsup: :cry: \
:sleepy: :yum: :triumph: :hand: :mask: \
:clap: :eyes: :gun: :persevere: :smiling_imp: \
:sweat: :broken_heart: :yellow_heart: :musical_note: :speak_no_evil: \
:wink: :skull: :confounded: :smile: :stuck_out_tongue_winking_eye: \
:angry: :no_good: :muscle: :facepunch: :purple_heart: \
:sparkling_heart: :blue_heart: :grimacing: :sparkles:".split(' ')

emoji_name_map = {}
for idx, alias in enumerate(EMOJIS):
    try:
        uni = emoji_lib.emojize(alias, language='alias')
        name = emoji_lib.demojize(uni).strip(':').replace(' ', '_')
        emoji_name_map[name] = idx
    except:
        pass

print(f"{len(emoji_name_map)} emojis mapped to names.")

def predict_emoji_for_texts(texts, model, st, top_k=5, batch_size=256):
    preds = []
    for i in range(0, len(texts), batch_size):
        batch = texts[i:i + batch_size]
        tokenized, _, _ = st.tokenize_sentences(batch)
        tokenized = torch.tensor(tokenized.astype(np.int64))

        with torch.no_grad():
            logits = model(tokenized)
            probs = torch.softmax(logits, dim=1).cpu().numpy()

        # indices of top-k predictions
        top_preds = np.argsort(probs, axis=1)[:, -top_k:][:, ::-1]
        preds.extend(top_preds.tolist())

    return preds

results = []
topk_values = [1, 2, 3, 4, 5]

for emoji_name, texts in tqdm(df_tweets_dict.items(), desc="Evaluating emojis"):
    if emoji_name not in emoji_name_map:
        continue

    if len(texts) > 5000:
        texts = texts.sample(5000, random_state=42)

    target_id = emoji_name_map[emoji_name]
    emoji_res = {"emoji": emoji_name}

    for k in topk_values:
        preds = predict_emoji_for_texts(list(texts), model, st, top_k=k)
        match_prop = np.mean([1 if target_id in p else 0 for p in preds])
        emoji_res[f"top@{k}"] = match_prop

    results.append(emoji_res)

deepmoji_df = pd.DataFrame(results)
deepmoji_df = deepmoji_df.sort_values('top@1', ascending=False).reset_index(drop=True)

print("\nDeepMoji evaluation completed.\n")
display(deepmoji_df)

print("Top-10 emojis by Top@1 accuracy:\n")
print(deepmoji_df.to_string(index=False))

Loading TorchMoji model and vocabulary...

/home/corentin/Documents/Oulu/textMining/project/torchMoji/torchmoji/model_def.py:159: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  nn.init.uniform(self.embed.weight.data, a=-0.5, b=0.5)
/home/corentin/Documents/Oulu/textMining/project/torchMoji/torchmoji/model_def.py:161: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(t)
/home/corentin/Documents/Oulu/textMining/project/torchMoji/torchmoji/model_def.py:163: UserWarning: nn.init.orthogonal is now deprecated in favor of nn.init.orthogonal_.
  nn.init.orthogonal(t)
/home/corentin/Documents/Oulu/textMining/project/torchMoji/torchmoji/model_def.py:165: UserWarning: nn.init.constant is now deprecated in favor of nn.init.constant_.
  nn.init.constant(t, 0)
/home/corentin/Documents/Oulu/textMining/project/torchMoji/torchmoji/model_def.py:167: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  nn.init.xavier_uniform(self.output_layer[0].weight.data)

Model loaded.
64 emojis mapped to names.

Evaluating emojis:   0%|          | 0/43 [00:00<?, ?it/s]/home/corentin/miniconda3/envs/affectiveComputing/lib/python3.7/site-packages/torch/nn/functional.py:1331: UserWarning: dropout2d: Received a 2-D input to dropout2d, which is deprecated and will result in an error in a future release. To retain the behavior and silence this warning, please use dropout instead. Note that dropout2d exists to provide channel-wise dropout on inputs with 2 spatial dimensions, a channel dimension, and an optional batch dimension (i.e. 3D or 4D inputs).
  warnings.warn(warn_msg)
/home/corentin/miniconda3/envs/affectiveComputing/lib/python3.7/site-packages/torch/nn/functional.py:1956: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
/home/corentin/miniconda3/envs/affectiveComputing/lib/python3.7/site-packages/torch/nn/modules/container.py:204: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)
Evaluating emojis: 100%|██████████| 43/43 [54:42<00:00, 76.33s/it]

DeepMoji evaluation completed.

                           emoji   top@1   top@2   top@3   top@4   top@5
0                      thumbs_up  0.3492  0.5020  0.5988  0.6598  0.7074
1                   winking_face  0.3070  0.4812  0.5682  0.6294  0.6754
2                   folded_hands  0.2938  0.3516  0.3934  0.4280  0.4592
3             face_savoring_food  0.1918  0.2256  0.2474  0.2672  0.2830
4   smiling_face_with_heart-eyes  0.1442  0.1992  0.2454  0.2890  0.3170
5         face_with_tears_of_joy  0.0916  0.1548  0.2134  0.2742  0.3270
6                           eyes  0.0910  0.1350  0.1642  0.1928  0.2182
7                          skull  0.0622  0.1040  0.1334  0.1610  0.1852
8   smiling_face_with_sunglasses  0.0528  0.0932  0.1394  0.1926  0.2628
9                       sparkles  0.0476  0.0734  0.0976  0.1218  0.1420
10            loudly_crying_face  0.0226  0.0584  0.1236  0.1606  0.1974
11                     red_heart  0.0194  0.0588  0.1266  0.1928  0.2580
12      grinning_face_with_sweat  0.0176  0.0392  0.0608  0.0886  0.1158
13                  smiling_face  0.0084  0.0336  0.0570  0.0882  0.1244
14     face_with_steam_from_nose  0.0048  0.0150  0.0730  0.1086  0.1374

Top-10 emojis by Top@1 accuracy:

                       emoji  top@1  top@2  top@3  top@4  top@5
                   thumbs_up 0.3492 0.5020 0.5988 0.6598 0.7074
                winking_face 0.3070 0.4812 0.5682 0.6294 0.6754
                folded_hands 0.2938 0.3516 0.3934 0.4280 0.4592
          face_savoring_food 0.1918 0.2256 0.2474 0.2672 0.2830
smiling_face_with_heart-eyes 0.1442 0.1992 0.2454 0.2890 0.3170
      face_with_tears_of_joy 0.0916 0.1548 0.2134 0.2742 0.3270
                        eyes 0.0910 0.1350 0.1642 0.1928 0.2182
                       skull 0.0622 0.1040 0.1334 0.1610 0.1852
smiling_face_with_sunglasses 0.0528 0.0932 0.1394 0.1926 0.2628
                    sparkles 0.0476 0.0734 0.0976 0.1218 0.1420
          loudly_crying_face 0.0226 0.0584 0.1236 0.1606 0.1974
                   red_heart 0.0194 0.0588 0.1266 0.1928 0.2580
    grinning_face_with_sweat 0.0176 0.0392 0.0608 0.0886 0.1158
                smiling_face 0.0084 0.0336 0.0570 0.0882 0.1244
   face_with_steam_from_nose 0.0048 0.0150 0.0730 0.1086 0.1374

In [6]:
# Emojis that are in df_tweets_dict but not in torchMoji model

for emoji_name, texts in tqdm(df_tweets_dict.items()):
    if emoji_name not in emoji_name_map:
        print(emoji_name)

100%|██████████| 43/43 [00:00<00:00, 95933.55it/s]

face_holding_back_tears
melting_face
check_mark_button
backhand_index_pointing_right
rolling_on_the_floor_laughing
thinking_face
enraged_face
pile_of_poo
rabbit_face
ghost
white_heart
cooking
hot_face
check_mark
smiling_face_with_hearts
fearful_face
clown_face
hatching_chick
partying_face
smiling_face_with_tear
party_popper
smiling_face_with_halo
egg
middle_finger
sun
saluting_face
fire
rabbit

# Question 10

In [56]:
from collections import Counter
from nltk.corpus import wordnet as wn, stopwords
from gensim.utils import simple_preprocess
import re

# Stopwords classiques + spécifiques à Twitter
stop = set(stopwords.words('english'))
extra_stop = {
    'co','https','http','amp','rt','im','youre','ive','get','got','one','us',
    'see','know','really','good','time','like','go','much','would','today',
    'love','thank','thanks','day','great','make','well','back','even','still',
    'think','want', 'easter', 'egg', 'thats', 'always', 'dont', 'literally', 'yall',
    'gonna', 'need', 'way', 'cant', 'also', 'going', 'right', 'didnt', 'never', 'people',
    'man', 'bro', 'say', 'said', 'hes', 'omg', 'look', 'stop', 'thing', 'ill'
}
stop |= extra_stop

def preprocess_text(text):
    text = re.sub(r'http\S+|www\S+|@\w+|#\w+', '', str(text))  # remove URLs, mentions, hashtags
    text = re.sub(r'[^a-zA-Z\s]', '', text)  # keep letters only
    return [w for w in simple_preprocess(text) if w not in stop and len(w) > 2]

def antonyms_of_word(w):
    ants = set()
    for syn in wn.synsets(w):
        for lemma in syn.lemmas():
            for ant in lemma.antonyms():
                ants.add(ant.name().lower().replace('_',' '))
    return ants

def top_n_terms_with_antonyms(texts, n=20, pool=200):
    toks = []
    for t in texts:
        toks.extend(preprocess_text(t))
    freq_words = [w for w, _ in Counter(toks).most_common(pool)]
    valid = [w for w in freq_words if len(antonyms_of_word(w)) > 1]
    return valid[:n]

def antonym_overlap(H1, H2):
    H1 = [h.lower() for h in H1]
    H2s = set(h.lower() for h in H2)
    matched = []
    for w in H1:
        ants = antonyms_of_word(w)
        if len(ants & H2s) > 0:
            matched.append((w, list(ants & H2s)))
    prop = len(matched) / len(H1) if len(H1) > 0 else 0
    return prop, matched

# 🔹 Exemple : sadness vs happiness
print("Available emoji keys:", list(df_tweets_dict.keys())[:10])

H_sad = top_n_terms_with_antonyms(df_tweets_dict['loudly_crying_face'], n=20)
H_joy = top_n_terms_with_antonyms(df_tweets_dict['smiling_face'], n=20)

print("\nFiltered sadness terms (with antonyms):", H_sad)
print("Filtered joy terms (with antonyms):", H_joy)

prop_sad_in_joy, matched_sad = antonym_overlap(H_sad, H_joy)
prop_joy_in_sad, matched_joy = antonym_overlap(H_joy, H_sad)

print("\nProportion of sadness words that have antonyms in joy:", round(prop_sad_in_joy,3))
print("Proportion of joy words that have antonyms in sadness:", round(prop_joy_in_sad,3))
print("\nExample antonym pairs (sad→joy):", matched_sad)
print("Example antonym pairs (joy→sad):", matched_joy)

Available emoji keys: ['face_holding_back_tears', 'face_savoring_food', 'thumbs_up', 'melting_face', 'check_mark_button', 'winking_face', 'backhand_index_pointing_right', 'rolling_on_the_floor_laughing', 'thinking_face', 'folded_hands']

Filtered sadness terms (with antonyms): ['first', 'bad', 'real', 'getting', 'show', 'take', 'made', 'whole', 'girl', 'new', 'miss', 'come', 'give', 'better', 'let', 'hard', 'best', 'went', 'end', 'little']
Filtered joy terms (with antonyms): ['new', 'best', 'work', 'first', 'welcome', 'take', 'better', 'little', 'made', 'friend', 'come', 'lets', 'friends', 'keep', 'getting', 'sure', 'give', 'let', 'long', 'start']

Proportion of sadness words that have antonyms in joy: 0.15
Proportion of joy words that have antonyms in sadness: 0.4

Example antonym pairs (sad→joy): [('take', ['give']), ('give', ['take']), ('went', ['come'])]
Example antonym pairs (joy→sad): [('best', ['bad']), ('first', ['end']), ('take', ['give']), ('better', ['bad']), ('keep', ['let']), ('getting', ['end']), ('give', ['take']), ('start', ['end'])]